package com.sunlight.blc.dao;

import com.sunlight.blc.model.Config;

public interface ConfigMapper extends BaseMapper<Config> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    Config selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_config
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    int updateByPrimaryKey(Config record);
}