package com.sunlight.blc.dao;

import com.sunlight.blc.model.Cost;

import java.util.List;

public interface CostMapper extends BaseMapper<Cost> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    int insertSelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    int updateByPrimaryKeySelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_cost
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    int updateByPrimaryKey(Cost record);

    Cost getLastOne(Cost record);

    List<Cost> getFromId(Cost record);
}