package com.sunlight.blc.dao;

import com.sunlight.blc.model.DailyProfit;

public interface DailyProfitMapper extends BaseMapper<DailyProfit> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    int insert(DailyProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    int insertSelective(DailyProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    DailyProfit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    int updateByPrimaryKeySelective(DailyProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_profit
     *
     * @mbg.generated Sat May 11 00:11:41 CST 2019
     */
    int updateByPrimaryKey(DailyProfit record);
}