package com.sunlight.blc.dao;

import com.sunlight.blc.model.DailyCurrency;

public interface DailyCurrencyMapper extends BaseMapper<DailyCurrency> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    int insert(DailyCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    int insertSelective(DailyCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    DailyCurrency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    int updateByPrimaryKeySelective(DailyCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_daily_currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    int updateByPrimaryKey(DailyCurrency record);
}