package com.sunlight.blc.dao;

import com.sunlight.blc.model.Deposit;

public interface DepositMapper extends BaseMapper<Deposit> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    int insert(Deposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    int insertSelective(Deposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    Deposit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    int updateByPrimaryKeySelective(Deposit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_deposit
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    int updateByPrimaryKey(Deposit record);

    String getLastUnfinishedId(Deposit record);
}