package com.sunlight.blc.dao;

import com.sunlight.blc.model.Exchange;

public interface ExchangeMapper extends BaseMapper<Exchange> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    Exchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_exchange
     *
     * @mbg.generated Tue May 07 14:01:35 CST 2019
     */
    int updateByPrimaryKey(Exchange record);
}