package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table composite_index
 *
 * @mbg.generated do_not_delete_during_merge Fri Aug 12 22:00:35 CST 2022
 */
public class CompositeIndex extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.id
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   上证A， 深成A，创业板
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.market
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.price
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private Double price;

    /**
     * Database Column Remarks:
     *   上涨下跌幅度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.up_percent
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private Double upPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.record_date
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private String recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.delstatus
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.remarks
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   成交量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.turn_over
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private Double turnOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column composite_index.market_name
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    private String marketName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.id
     *
     * @return the value of composite_index.id
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.id
     *
     * @param id the value for composite_index.id
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.market
     *
     * @return the value of composite_index.market
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.market
     *
     * @param market the value for composite_index.market
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.price
     *
     * @return the value of composite_index.price
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.price
     *
     * @param price the value for composite_index.price
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.up_percent
     *
     * @return the value of composite_index.up_percent
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public Double getUpPercent() {
        return upPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.up_percent
     *
     * @param upPercent the value for composite_index.up_percent
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setUpPercent(Double upPercent) {
        this.upPercent = upPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.record_date
     *
     * @return the value of composite_index.record_date
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.record_date
     *
     * @param recordDate the value for composite_index.record_date
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.delstatus
     *
     * @return the value of composite_index.delstatus
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.delstatus
     *
     * @param delstatus the value for composite_index.delstatus
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.remarks
     *
     * @return the value of composite_index.remarks
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.remarks
     *
     * @param remarks the value for composite_index.remarks
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.turn_over
     *
     * @return the value of composite_index.turn_over
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public Double getTurnOver() {
        return turnOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.turn_over
     *
     * @param turnOver the value for composite_index.turn_over
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setTurnOver(Double turnOver) {
        this.turnOver = turnOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column composite_index.market_name
     *
     * @return the value of composite_index.market_name
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column composite_index.market_name
     *
     * @param marketName the value for composite_index.market_name
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName == null ? null : marketName.trim();
    }
}