package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table invest_user
 *
 * @mbg.generated do_not_delete_during_merge Mon Aug 01 20:31:03 CST 2022
 */
public class InvestUser extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_user.id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_user.user_name
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_user.remarks
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_user.delstatus
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_user.company_id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_user.id
     *
     * @return the value of invest_user.id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_user.id
     *
     * @param id the value for invest_user.id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_user.user_name
     *
     * @return the value of invest_user.user_name
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_user.user_name
     *
     * @param userName the value for invest_user.user_name
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_user.remarks
     *
     * @return the value of invest_user.remarks
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_user.remarks
     *
     * @param remarks the value for invest_user.remarks
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_user.delstatus
     *
     * @return the value of invest_user.delstatus
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_user.delstatus
     *
     * @param delstatus the value for invest_user.delstatus
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_user.company_id
     *
     * @return the value of invest_user.company_id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_user.company_id
     *
     * @param companyId the value for invest_user.company_id
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}