package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table policy_price
 *
 * @mbg.generated do_not_delete_during_merge Sat Aug 06 13:28:02 CST 2022
 */
public class PolicyPrice extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.id
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.code
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.name
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String name;

    /**
     * Database Column Remarks:
     *   价格列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.prices
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String prices;

    /**
     * Database Column Remarks:
     *   20日高价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newHigh20;

    /**
     * Database Column Remarks:
     *   60日高价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newHigh60;

    /**
     * Database Column Remarks:
     *   90日高价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newHigh90;

    /**
     * Database Column Remarks:
     *   120日高价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newHigh120;

    /**
     * Database Column Remarks:
     *   历史最高
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newHighEst;

    /**
     * Database Column Remarks:
     *   20日高价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newLow20;

    /**
     * Database Column Remarks:
     *   60日低价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newLow60;

    /**
     * Database Column Remarks:
     *   90日低价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newLow90;

    /**
     * Database Column Remarks:
     *   120日低价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newLow120;

    /**
     * Database Column Remarks:
     *   历史最低
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Double newLowEst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.delstatus
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   20日高价日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newHigh20Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newHigh60Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newHigh90Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newHigh120Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_high_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newHighEstDate;

    /**
     * Database Column Remarks:
     *   20日高价日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newLow20Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newLow60Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newLow90Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newLow120Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.new_low_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String newLowEstDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_price.remarks
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.id
     *
     * @return the value of policy_price.id
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.id
     *
     * @param id the value for policy_price.id
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.code
     *
     * @return the value of policy_price.code
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.code
     *
     * @param code the value for policy_price.code
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.name
     *
     * @return the value of policy_price.name
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.name
     *
     * @param name the value for policy_price.name
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.prices
     *
     * @return the value of policy_price.prices
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getPrices() {
        return prices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.prices
     *
     * @param prices the value for policy_price.prices
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setPrices(String prices) {
        this.prices = prices == null ? null : prices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_20
     *
     * @return the value of policy_price.new_high_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewHigh20() {
        return newHigh20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_20
     *
     * @param newHigh20 the value for policy_price.new_high_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh20(Double newHigh20) {
        this.newHigh20 = newHigh20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_60
     *
     * @return the value of policy_price.new_high_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewHigh60() {
        return newHigh60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_60
     *
     * @param newHigh60 the value for policy_price.new_high_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh60(Double newHigh60) {
        this.newHigh60 = newHigh60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_90
     *
     * @return the value of policy_price.new_high_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewHigh90() {
        return newHigh90;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_90
     *
     * @param newHigh90 the value for policy_price.new_high_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh90(Double newHigh90) {
        this.newHigh90 = newHigh90;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_120
     *
     * @return the value of policy_price.new_high_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewHigh120() {
        return newHigh120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_120
     *
     * @param newHigh120 the value for policy_price.new_high_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh120(Double newHigh120) {
        this.newHigh120 = newHigh120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_est
     *
     * @return the value of policy_price.new_high_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewHighEst() {
        return newHighEst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_est
     *
     * @param newHighEst the value for policy_price.new_high_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHighEst(Double newHighEst) {
        this.newHighEst = newHighEst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_20
     *
     * @return the value of policy_price.new_low_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewLow20() {
        return newLow20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_20
     *
     * @param newLow20 the value for policy_price.new_low_20
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow20(Double newLow20) {
        this.newLow20 = newLow20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_60
     *
     * @return the value of policy_price.new_low_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewLow60() {
        return newLow60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_60
     *
     * @param newLow60 the value for policy_price.new_low_60
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow60(Double newLow60) {
        this.newLow60 = newLow60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_90
     *
     * @return the value of policy_price.new_low_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewLow90() {
        return newLow90;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_90
     *
     * @param newLow90 the value for policy_price.new_low_90
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow90(Double newLow90) {
        this.newLow90 = newLow90;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_120
     *
     * @return the value of policy_price.new_low_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewLow120() {
        return newLow120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_120
     *
     * @param newLow120 the value for policy_price.new_low_120
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow120(Double newLow120) {
        this.newLow120 = newLow120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_est
     *
     * @return the value of policy_price.new_low_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Double getNewLowEst() {
        return newLowEst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_est
     *
     * @param newLowEst the value for policy_price.new_low_est
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLowEst(Double newLowEst) {
        this.newLowEst = newLowEst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.delstatus
     *
     * @return the value of policy_price.delstatus
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.delstatus
     *
     * @param delstatus the value for policy_price.delstatus
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_20_date
     *
     * @return the value of policy_price.new_high_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewHigh20Date() {
        return newHigh20Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_20_date
     *
     * @param newHigh20Date the value for policy_price.new_high_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh20Date(String newHigh20Date) {
        this.newHigh20Date = newHigh20Date == null ? null : newHigh20Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_60_date
     *
     * @return the value of policy_price.new_high_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewHigh60Date() {
        return newHigh60Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_60_date
     *
     * @param newHigh60Date the value for policy_price.new_high_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh60Date(String newHigh60Date) {
        this.newHigh60Date = newHigh60Date == null ? null : newHigh60Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_90_date
     *
     * @return the value of policy_price.new_high_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewHigh90Date() {
        return newHigh90Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_90_date
     *
     * @param newHigh90Date the value for policy_price.new_high_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh90Date(String newHigh90Date) {
        this.newHigh90Date = newHigh90Date == null ? null : newHigh90Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_120_date
     *
     * @return the value of policy_price.new_high_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewHigh120Date() {
        return newHigh120Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_120_date
     *
     * @param newHigh120Date the value for policy_price.new_high_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHigh120Date(String newHigh120Date) {
        this.newHigh120Date = newHigh120Date == null ? null : newHigh120Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_high_est_date
     *
     * @return the value of policy_price.new_high_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewHighEstDate() {
        return newHighEstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_high_est_date
     *
     * @param newHighEstDate the value for policy_price.new_high_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewHighEstDate(String newHighEstDate) {
        this.newHighEstDate = newHighEstDate == null ? null : newHighEstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_20_date
     *
     * @return the value of policy_price.new_low_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewLow20Date() {
        return newLow20Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_20_date
     *
     * @param newLow20Date the value for policy_price.new_low_20_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow20Date(String newLow20Date) {
        this.newLow20Date = newLow20Date == null ? null : newLow20Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_60_date
     *
     * @return the value of policy_price.new_low_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewLow60Date() {
        return newLow60Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_60_date
     *
     * @param newLow60Date the value for policy_price.new_low_60_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow60Date(String newLow60Date) {
        this.newLow60Date = newLow60Date == null ? null : newLow60Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_90_date
     *
     * @return the value of policy_price.new_low_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewLow90Date() {
        return newLow90Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_90_date
     *
     * @param newLow90Date the value for policy_price.new_low_90_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow90Date(String newLow90Date) {
        this.newLow90Date = newLow90Date == null ? null : newLow90Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_120_date
     *
     * @return the value of policy_price.new_low_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewLow120Date() {
        return newLow120Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_120_date
     *
     * @param newLow120Date the value for policy_price.new_low_120_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLow120Date(String newLow120Date) {
        this.newLow120Date = newLow120Date == null ? null : newLow120Date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.new_low_est_date
     *
     * @return the value of policy_price.new_low_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getNewLowEstDate() {
        return newLowEstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.new_low_est_date
     *
     * @param newLowEstDate the value for policy_price.new_low_est_date
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setNewLowEstDate(String newLowEstDate) {
        this.newLowEstDate = newLowEstDate == null ? null : newLowEstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_price.remarks
     *
     * @return the value of policy_price.remarks
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_price.remarks
     *
     * @param remarks the value for policy_price.remarks
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}