package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table policy_limit
 *
 * @mbg.generated do_not_delete_during_merge Thu Aug 04 16:21:35 CST 2022
 */
public class PolicyLimit extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.id
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.code
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.name
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.plates
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private String plates;

    /**
     * Database Column Remarks:
     *   涨停或者跌停
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.limit_type
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Integer limitType;

    /**
     * Database Column Remarks:
     *   涨停或者跌停天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.days
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Integer days;

    /**
     * Database Column Remarks:
     *   涨跌停日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.limit_date
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private String limitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.remarks
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   软删除标志位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.delstatus
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   当前价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.current_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Double currentPrice;

    /**
     * Database Column Remarks:
     *   涨跌幅度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.up_percent
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Double upPercent;

    /**
     * Database Column Remarks:
     *   当天最高价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.highest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Double highestPrice;

    /**
     * Database Column Remarks:
     *   当天最低价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_limit.lowest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    private Double lowestPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.id
     *
     * @return the value of policy_limit.id
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.id
     *
     * @param id the value for policy_limit.id
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.code
     *
     * @return the value of policy_limit.code
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.code
     *
     * @param code the value for policy_limit.code
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.name
     *
     * @return the value of policy_limit.name
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.name
     *
     * @param name the value for policy_limit.name
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.plates
     *
     * @return the value of policy_limit.plates
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public String getPlates() {
        return plates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.plates
     *
     * @param plates the value for policy_limit.plates
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setPlates(String plates) {
        this.plates = plates == null ? null : plates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.limit_type
     *
     * @return the value of policy_limit.limit_type
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Integer getLimitType() {
        return limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.limit_type
     *
     * @param limitType the value for policy_limit.limit_type
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setLimitType(Integer limitType) {
        this.limitType = limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.days
     *
     * @return the value of policy_limit.days
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.days
     *
     * @param days the value for policy_limit.days
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.limit_date
     *
     * @return the value of policy_limit.limit_date
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public String getLimitDate() {
        return limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.limit_date
     *
     * @param limitDate the value for policy_limit.limit_date
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setLimitDate(String limitDate) {
        this.limitDate = limitDate == null ? null : limitDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.remarks
     *
     * @return the value of policy_limit.remarks
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.remarks
     *
     * @param remarks the value for policy_limit.remarks
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.delstatus
     *
     * @return the value of policy_limit.delstatus
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.delstatus
     *
     * @param delstatus the value for policy_limit.delstatus
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.current_price
     *
     * @return the value of policy_limit.current_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Double getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.current_price
     *
     * @param currentPrice the value for policy_limit.current_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.up_percent
     *
     * @return the value of policy_limit.up_percent
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Double getUpPercent() {
        return upPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.up_percent
     *
     * @param upPercent the value for policy_limit.up_percent
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setUpPercent(Double upPercent) {
        this.upPercent = upPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.highest_price
     *
     * @return the value of policy_limit.highest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Double getHighestPrice() {
        return highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.highest_price
     *
     * @param highestPrice the value for policy_limit.highest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setHighestPrice(Double highestPrice) {
        this.highestPrice = highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_limit.lowest_price
     *
     * @return the value of policy_limit.lowest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public Double getLowestPrice() {
        return lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_limit.lowest_price
     *
     * @param lowestPrice the value for policy_limit.lowest_price
     *
     * @mbg.generated Thu Aug 04 16:21:35 CST 2022
     */
    public void setLowestPrice(Double lowestPrice) {
        this.lowestPrice = lowestPrice;
    }
}