package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table policy_sel_high_low_notify
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 10 16:46:28 CST 2022
 */
public class PolicySelHighLowNotify extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.id
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.code
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.name
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.prices
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String prices;

    /**
     * Database Column Remarks:
     *   最高还是最低的通知类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.notify_type
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer notifyType;

    /**
     * Database Column Remarks:
     *   通知时的价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.notify_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double notifyPrice;

    /**
     * Database Column Remarks:
     *   是否买入
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.has_buy
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer hasBuy;

    /**
     * Database Column Remarks:
     *   买入价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.buy_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double buyPrice;

    /**
     * Database Column Remarks:
     *   是否卖出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.has_sell
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer hasSell;

    /**
     * Database Column Remarks:
     *   卖出价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.sell_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double sellPrice;

    /**
     * Database Column Remarks:
     *   收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double profit;

    /**
     * Database Column Remarks:
     *   30天内最好收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.best_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double bestProfit;

    /**
     * Database Column Remarks:
     *   30天内最差收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.bad_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double badProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.remarks
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.delstatus
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   记录日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.notify_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String notifyDate;

    /**
     * Database Column Remarks:
     *   记录天数，目前记录30天记录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.days
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Integer days;

    /**
     * Database Column Remarks:
     *   购买日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.buy_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String buyDate;

    /**
     * Database Column Remarks:
     *   卖出日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.sell_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String sellDate;

    /**
     * Database Column Remarks:
     *   30日内最高日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.high_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String highEstDate;

    /**
     * Database Column Remarks:
     *   30日内最低日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.low_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private String lowEstDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.high_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double highEstPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_sel_high_low_notify.low_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    private Double lowEstPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.id
     *
     * @return the value of policy_sel_high_low_notify.id
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.id
     *
     * @param id the value for policy_sel_high_low_notify.id
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.code
     *
     * @return the value of policy_sel_high_low_notify.code
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.code
     *
     * @param code the value for policy_sel_high_low_notify.code
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.name
     *
     * @return the value of policy_sel_high_low_notify.name
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.name
     *
     * @param name the value for policy_sel_high_low_notify.name
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.prices
     *
     * @return the value of policy_sel_high_low_notify.prices
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getPrices() {
        return prices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.prices
     *
     * @param prices the value for policy_sel_high_low_notify.prices
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setPrices(String prices) {
        this.prices = prices == null ? null : prices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.notify_type
     *
     * @return the value of policy_sel_high_low_notify.notify_type
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.notify_type
     *
     * @param notifyType the value for policy_sel_high_low_notify.notify_type
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setNotifyType(Integer notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.notify_price
     *
     * @return the value of policy_sel_high_low_notify.notify_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getNotifyPrice() {
        return notifyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.notify_price
     *
     * @param notifyPrice the value for policy_sel_high_low_notify.notify_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setNotifyPrice(Double notifyPrice) {
        this.notifyPrice = notifyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.has_buy
     *
     * @return the value of policy_sel_high_low_notify.has_buy
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getHasBuy() {
        return hasBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.has_buy
     *
     * @param hasBuy the value for policy_sel_high_low_notify.has_buy
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setHasBuy(Integer hasBuy) {
        this.hasBuy = hasBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.buy_price
     *
     * @return the value of policy_sel_high_low_notify.buy_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.buy_price
     *
     * @param buyPrice the value for policy_sel_high_low_notify.buy_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.has_sell
     *
     * @return the value of policy_sel_high_low_notify.has_sell
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getHasSell() {
        return hasSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.has_sell
     *
     * @param hasSell the value for policy_sel_high_low_notify.has_sell
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setHasSell(Integer hasSell) {
        this.hasSell = hasSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.sell_price
     *
     * @return the value of policy_sel_high_low_notify.sell_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.sell_price
     *
     * @param sellPrice the value for policy_sel_high_low_notify.sell_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.profit
     *
     * @return the value of policy_sel_high_low_notify.profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.profit
     *
     * @param profit the value for policy_sel_high_low_notify.profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.best_profit
     *
     * @return the value of policy_sel_high_low_notify.best_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getBestProfit() {
        return bestProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.best_profit
     *
     * @param bestProfit the value for policy_sel_high_low_notify.best_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setBestProfit(Double bestProfit) {
        this.bestProfit = bestProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.bad_profit
     *
     * @return the value of policy_sel_high_low_notify.bad_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getBadProfit() {
        return badProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.bad_profit
     *
     * @param badProfit the value for policy_sel_high_low_notify.bad_profit
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setBadProfit(Double badProfit) {
        this.badProfit = badProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.remarks
     *
     * @return the value of policy_sel_high_low_notify.remarks
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.remarks
     *
     * @param remarks the value for policy_sel_high_low_notify.remarks
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.delstatus
     *
     * @return the value of policy_sel_high_low_notify.delstatus
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.delstatus
     *
     * @param delstatus the value for policy_sel_high_low_notify.delstatus
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.notify_date
     *
     * @return the value of policy_sel_high_low_notify.notify_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getNotifyDate() {
        return notifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.notify_date
     *
     * @param notifyDate the value for policy_sel_high_low_notify.notify_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setNotifyDate(String notifyDate) {
        this.notifyDate = notifyDate == null ? null : notifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.days
     *
     * @return the value of policy_sel_high_low_notify.days
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.days
     *
     * @param days the value for policy_sel_high_low_notify.days
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.buy_date
     *
     * @return the value of policy_sel_high_low_notify.buy_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.buy_date
     *
     * @param buyDate the value for policy_sel_high_low_notify.buy_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate == null ? null : buyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.sell_date
     *
     * @return the value of policy_sel_high_low_notify.sell_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.sell_date
     *
     * @param sellDate the value for policy_sel_high_low_notify.sell_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setSellDate(String sellDate) {
        this.sellDate = sellDate == null ? null : sellDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.high_est_date
     *
     * @return the value of policy_sel_high_low_notify.high_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getHighEstDate() {
        return highEstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.high_est_date
     *
     * @param highEstDate the value for policy_sel_high_low_notify.high_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setHighEstDate(String highEstDate) {
        this.highEstDate = highEstDate == null ? null : highEstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.low_est_date
     *
     * @return the value of policy_sel_high_low_notify.low_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public String getLowEstDate() {
        return lowEstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.low_est_date
     *
     * @param lowEstDate the value for policy_sel_high_low_notify.low_est_date
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setLowEstDate(String lowEstDate) {
        this.lowEstDate = lowEstDate == null ? null : lowEstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.high_est_price
     *
     * @return the value of policy_sel_high_low_notify.high_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getHighEstPrice() {
        return highEstPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.high_est_price
     *
     * @param highEstPrice the value for policy_sel_high_low_notify.high_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setHighEstPrice(Double highEstPrice) {
        this.highEstPrice = highEstPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_sel_high_low_notify.low_est_price
     *
     * @return the value of policy_sel_high_low_notify.low_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public Double getLowEstPrice() {
        return lowEstPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_sel_high_low_notify.low_est_price
     *
     * @param lowEstPrice the value for policy_sel_high_low_notify.low_est_price
     *
     * @mbg.generated Wed Aug 10 16:46:28 CST 2022
     */
    public void setLowEstPrice(Double lowEstPrice) {
        this.lowEstPrice = lowEstPrice;
    }
}