package com.sunlight.invest.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table profit
 *
 * @mbg.generated do_not_delete_during_merge Mon Aug 01 23:17:30 CST 2022
 */
public class Profit extends BaseObject {
    /**
     * Database Column Remarks:
     *   primariy key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   交易时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.date
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Date date;

    /**
     * Database Column Remarks:
     *   交易人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.user_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   股票名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.stock_name
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private String stockName;

    /**
     * Database Column Remarks:
     *   盈利
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Double profit;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.remarks
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   是否结算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.settled
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Integer settled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profit.company_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.id
     *
     * @return the value of profit.id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.id
     *
     * @param id the value for profit.id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.date
     *
     * @return the value of profit.date
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.date
     *
     * @param date the value for profit.date
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.user_id
     *
     * @return the value of profit.user_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.user_id
     *
     * @param userId the value for profit.user_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.stock_name
     *
     * @return the value of profit.stock_name
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.stock_name
     *
     * @param stockName the value for profit.stock_name
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.profit
     *
     * @return the value of profit.profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.profit
     *
     * @param profit the value for profit.profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.remarks
     *
     * @return the value of profit.remarks
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.remarks
     *
     * @param remarks the value for profit.remarks
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.settled
     *
     * @return the value of profit.settled
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Integer getSettled() {
        return settled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.settled
     *
     * @param settled the value for profit.settled
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setSettled(Integer settled) {
        this.settled = settled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profit.company_id
     *
     * @return the value of profit.company_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profit.company_id
     *
     * @param companyId the value for profit.company_id
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}