package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sel_stock
 *
 * @mbg.generated do_not_delete_during_merge Mon Aug 01 22:56:19 CST 2022
 */
public class SelStock extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.name
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.code
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.delstatus
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.remarks
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.is_third
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private Integer isThird;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sel_stock.company_id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.id
     *
     * @return the value of sel_stock.id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.id
     *
     * @param id the value for sel_stock.id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.name
     *
     * @return the value of sel_stock.name
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.name
     *
     * @param name the value for sel_stock.name
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.code
     *
     * @return the value of sel_stock.code
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.code
     *
     * @param code the value for sel_stock.code
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.delstatus
     *
     * @return the value of sel_stock.delstatus
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.delstatus
     *
     * @param delstatus the value for sel_stock.delstatus
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.remarks
     *
     * @return the value of sel_stock.remarks
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.remarks
     *
     * @param remarks the value for sel_stock.remarks
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.is_third
     *
     * @return the value of sel_stock.is_third
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public Integer getIsThird() {
        return isThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.is_third
     *
     * @param isThird the value for sel_stock.is_third
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setIsThird(Integer isThird) {
        this.isThird = isThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sel_stock.company_id
     *
     * @return the value of sel_stock.company_id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sel_stock.company_id
     *
     * @param companyId the value for sel_stock.company_id
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}