package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table stocks
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 03 15:37:39 CST 2022
 */
public class Stocks extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.id
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.code
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.name
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.delstatus
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.list_time
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private String listTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.remarks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   股票所属板块
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.plates
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    private String plates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.id
     *
     * @return the value of stocks.id
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.id
     *
     * @param id the value for stocks.id
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.code
     *
     * @return the value of stocks.code
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.code
     *
     * @param code the value for stocks.code
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.name
     *
     * @return the value of stocks.name
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.name
     *
     * @param name the value for stocks.name
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.delstatus
     *
     * @return the value of stocks.delstatus
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.delstatus
     *
     * @param delstatus the value for stocks.delstatus
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.list_time
     *
     * @return the value of stocks.list_time
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public String getListTime() {
        return listTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.list_time
     *
     * @param listTime the value for stocks.list_time
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setListTime(String listTime) {
        this.listTime = listTime == null ? null : listTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.remarks
     *
     * @return the value of stocks.remarks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.remarks
     *
     * @param remarks the value for stocks.remarks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.plates
     *
     * @return the value of stocks.plates
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public String getPlates() {
        return plates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.plates
     *
     * @param plates the value for stocks.plates
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    public void setPlates(String plates) {
        this.plates = plates == null ? null : plates.trim();
    }
}