package com.sunlight.invest.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trade_date
 *
 * @mbg.generated do_not_delete_during_merge Fri Aug 05 16:44:35 CST 2022
 */
public class TradeDate extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_date.id
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   交易日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_date.t_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    private String tDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_date.delstatus
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    private Integer delstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_date.id
     *
     * @return the value of trade_date.id
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_date.id
     *
     * @param id the value for trade_date.id
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_date.t_date
     *
     * @return the value of trade_date.t_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public String gettDate() {
        return tDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_date.t_date
     *
     * @param tDate the value for trade_date.t_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public void settDate(String tDate) {
        this.tDate = tDate == null ? null : tDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_date.delstatus
     *
     * @return the value of trade_date.delstatus
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_date.delstatus
     *
     * @param delstatus the value for trade_date.delstatus
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }
}