package com.sunlight.portal.accounts.dao;

import com.sunlight.portal.accounts.model.Company;

public interface CompanyMapper extends BaseMapper<Company> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    int updateByPrimaryKey(Company record);
}