package com.sunlight.portal.accounts.dao;

import com.sunlight.portal.accounts.model.Company;

public interface CompanyMapper extends BaseMapper<Company> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_company
     *
     * @mbg.generated Fri Mar 03 13:20:15 CST 2023
     */
    int updateByPrimaryKey(Company record);
}