package com.sunlight.portal.accounts.dao;

import com.sunlight.portal.accounts.model.UserRole;

public interface UserRoleMapper extends BaseMapper<UserRoleMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sl_user_role
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    int updateByPrimaryKey(UserRole record);
}