package com.sunlight.portal.accounts.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table company
 *
 * @mbg.generated do_not_delete_during_merge Mon Aug 01 16:27:05 CST 2022
 */
public class Company extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private String name;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.remarks
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   消息推送地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.push_url
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private String pushUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.delstatus
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    private Integer delstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.remarks
     *
     * @return the value of company.remarks
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.remarks
     *
     * @param remarks the value for company.remarks
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.push_url
     *
     * @return the value of company.push_url
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public String getPushUrl() {
        return pushUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.push_url
     *
     * @param pushUrl the value for company.push_url
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setPushUrl(String pushUrl) {
        this.pushUrl = pushUrl == null ? null : pushUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.delstatus
     *
     * @return the value of company.delstatus
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.delstatus
     *
     * @param delstatus the value for company.delstatus
     *
     * @mbg.generated Mon Aug 01 16:27:05 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }
}