package com.sunlight.portal.accounts.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table configs
 *
 * @mbg.generated do_not_delete_during_merge Fri Jul 15 17:49:05 CST 2022
 */
public class Configs extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configs.id
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configs.item_key
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    private String itemKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configs.desc
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    private String itemDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configs.delstatus
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configs.item_value
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    private String itemValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configs.id
     *
     * @return the value of configs.id
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configs.id
     *
     * @param id the value for configs.id
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configs.item_key
     *
     * @return the value of configs.item_key
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public String getItemKey() {
        return itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configs.item_key
     *
     * @param itemKey the value for configs.item_key
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public void setItemKey(String itemKey) {
        this.itemKey = itemKey == null ? null : itemKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configs.desc
     *
     * @return the value of configs.desc
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configs.desc
     *
     * @param desc the value for configs.desc
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public void setItemDesc(String desc) {
        this.itemDesc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configs.delstatus
     *
     * @return the value of configs.delstatus
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configs.delstatus
     *
     * @param delstatus the value for configs.delstatus
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configs.item_value
     *
     * @return the value of configs.item_value
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configs.item_value
     *
     * @param itemValue the value for configs.item_value
     *
     * @mbg.generated Fri Jul 15 17:49:05 CST 2022
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue == null ? null : itemValue.trim();
    }
}