package com.sunlight.portal.accounts.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sl_menu
 *
 * @mbg.generated do_not_delete_during_merge Fri Mar 03 13:20:05 CST 2023
 */
public class Menu extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.id
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.menu_name
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.menu_code
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.menu_url
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.delstatus
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_menu.remarks
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.id
     *
     * @return the value of sl_menu.id
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.id
     *
     * @param id the value for sl_menu.id
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.menu_name
     *
     * @return the value of sl_menu.menu_name
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.menu_name
     *
     * @param menuName the value for sl_menu.menu_name
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.menu_code
     *
     * @return the value of sl_menu.menu_code
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.menu_code
     *
     * @param menuCode the value for sl_menu.menu_code
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.menu_url
     *
     * @return the value of sl_menu.menu_url
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.menu_url
     *
     * @param menuUrl the value for sl_menu.menu_url
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.delstatus
     *
     * @return the value of sl_menu.delstatus
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.delstatus
     *
     * @param delstatus the value for sl_menu.delstatus
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_menu.remarks
     *
     * @return the value of sl_menu.remarks
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_menu.remarks
     *
     * @param remarks the value for sl_menu.remarks
     *
     * @mbg.generated Fri Mar 03 13:20:05 CST 2023
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}