package com.sunlight.portal.accounts.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sl_user_role
 *
 * @mbg.generated do_not_delete_during_merge Fri Mar 03 13:19:27 CST 2023
 */
public class UserRole extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.id
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.role_name
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   角色code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.role_code
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private String roleCode;

    /**
     * Database Column Remarks:
     *   删除标志位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.delstatus
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   角色描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.remarks
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   角色权限点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sl_user_role.access_points
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    private String accessPoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.id
     *
     * @return the value of sl_user_role.id
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.id
     *
     * @param id the value for sl_user_role.id
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.role_name
     *
     * @return the value of sl_user_role.role_name
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.role_name
     *
     * @param roleName the value for sl_user_role.role_name
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.role_code
     *
     * @return the value of sl_user_role.role_code
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.role_code
     *
     * @param roleCode the value for sl_user_role.role_code
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.delstatus
     *
     * @return the value of sl_user_role.delstatus
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.delstatus
     *
     * @param delstatus the value for sl_user_role.delstatus
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.remarks
     *
     * @return the value of sl_user_role.remarks
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.remarks
     *
     * @param remarks the value for sl_user_role.remarks
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sl_user_role.access_points
     *
     * @return the value of sl_user_role.access_points
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public String getAccessPoints() {
        return accessPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sl_user_role.access_points
     *
     * @param accessPoints the value for sl_user_role.access_points
     *
     * @mbg.generated Fri Mar 03 13:19:27 CST 2023
     */
    public void setAccessPoints(String accessPoints) {
        this.accessPoints = accessPoints == null ? null : accessPoints.trim();
    }
}