package com.sunlight.invest.dao;

import com.sunlight.invest.model.CompositeIndex;

public interface CompositeIndexMapper extends BaseMapper<CompositeIndex> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    int insert(CompositeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    int insertSelective(CompositeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    CompositeIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    int updateByPrimaryKeySelective(CompositeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table composite_index
     *
     * @mbg.generated Fri Aug 12 22:00:35 CST 2022
     */
    int updateByPrimaryKey(CompositeIndex record);
}