package com.sunlight.invest.dao;

import com.sunlight.invest.model.InvestUser;

public interface InvestUserMapper extends BaseMapper<InvestUser> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    int insert(InvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    int insertSelective(InvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    InvestUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    int updateByPrimaryKeySelective(InvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invest_user
     *
     * @mbg.generated Mon Aug 01 20:31:03 CST 2022
     */
    int updateByPrimaryKey(InvestUser record);
}