package com.sunlight.invest.dao;

import com.sunlight.invest.model.PolicyPrice;

public interface PolicyPriceMapper extends BaseMapper<PolicyPrice> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    int insert(PolicyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    int insertSelective(PolicyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    PolicyPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    int updateByPrimaryKeySelective(PolicyPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_price
     *
     * @mbg.generated Sat Aug 06 13:28:02 CST 2022
     */
    int updateByPrimaryKey(PolicyPrice record);
}