package com.sunlight.invest.dao;

import com.sunlight.invest.model.Profit;

public interface ProfitMapper extends BaseMapper<Profit> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    int insert(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    int insertSelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    Profit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    int updateByPrimaryKeySelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit
     *
     * @mbg.generated Mon Aug 01 23:17:30 CST 2022
     */
    int updateByPrimaryKey(Profit record);

    int updateSettled(Profit record);
}