package com.sunlight.invest.dao;

import com.sunlight.invest.model.SelStock;

public interface SelStockMapper extends BaseMapper<SelStock> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    int insert(SelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    int insertSelective(SelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    SelStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    int updateByPrimaryKeySelective(SelStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sel_stock
     *
     * @mbg.generated Mon Aug 01 22:56:19 CST 2022
     */
    int updateByPrimaryKey(SelStock record);
}