package com.sunlight.invest.dao;

import com.sunlight.invest.model.Stocks;

public interface StocksMapper extends BaseMapper<Stocks> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    int insert(Stocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    int insertSelective(Stocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    Stocks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    int updateByPrimaryKeySelective(Stocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocks
     *
     * @mbg.generated Wed Aug 03 15:37:39 CST 2022
     */
    int updateByPrimaryKey(Stocks record);
}