package com.sunlight.invest.dao;

import com.sunlight.invest.model.TradeDate;

public interface TradeDateMapper extends BaseMapper<TradeDate> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    int insert(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    int insertSelective(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    TradeDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    int updateByPrimaryKeySelective(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated Fri Aug 05 16:44:35 CST 2022
     */
    int updateByPrimaryKey(TradeDate record);
}