package com.sunlight.blc.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blc_config
 *
 * @mbg.generated do_not_delete_during_merge Tue May 07 16:14:56 CST 2019
 */
public class Config extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_config.id
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_config.delstatus
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_config.key_item
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    private String keyItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_config.value
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_config.remarks
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_config.id
     *
     * @return the value of blc_config.id
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_config.id
     *
     * @param id the value for blc_config.id
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_config.delstatus
     *
     * @return the value of blc_config.delstatus
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_config.delstatus
     *
     * @param delstatus the value for blc_config.delstatus
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_config.key_item
     *
     * @return the value of blc_config.key_item
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public String getKeyItem() {
        return keyItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_config.key_item
     *
     * @param keyItem the value for blc_config.key_item
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public void setKeyItem(String keyItem) {
        this.keyItem = keyItem == null ? null : keyItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_config.value
     *
     * @return the value of blc_config.value
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_config.value
     *
     * @param value the value for blc_config.value
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_config.remarks
     *
     * @return the value of blc_config.remarks
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_config.remarks
     *
     * @param remarks the value for blc_config.remarks
     *
     * @mbg.generated Tue May 07 16:14:56 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}