package com.sunlight.blc.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blc_cost
 *
 * @mbg.generated do_not_delete_during_merge Fri May 10 20:47:13 CST 2019
 */
public class Cost extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.id
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.delstatus
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   花费数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.amount
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private Double amount;

    /**
     * Database Column Remarks:
     *   时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.datatime
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private Date datatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.balance
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private Double balance;

    /**
     * Database Column Remarks:
     *   花费详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.details
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private String details;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_cost.remarks
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.id
     *
     * @return the value of blc_cost.id
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.id
     *
     * @param id the value for blc_cost.id
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.delstatus
     *
     * @return the value of blc_cost.delstatus
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.delstatus
     *
     * @param delstatus the value for blc_cost.delstatus
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.amount
     *
     * @return the value of blc_cost.amount
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.amount
     *
     * @param amount the value for blc_cost.amount
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.datatime
     *
     * @return the value of blc_cost.datatime
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public Date getDatatime() {
        return datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.datatime
     *
     * @param datatime the value for blc_cost.datatime
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setDatatime(Date datatime) {
        this.datatime = datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.balance
     *
     * @return the value of blc_cost.balance
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.balance
     *
     * @param balance the value for blc_cost.balance
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.details
     *
     * @return the value of blc_cost.details
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.details
     *
     * @param details the value for blc_cost.details
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_cost.remarks
     *
     * @return the value of blc_cost.remarks
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_cost.remarks
     *
     * @param remarks the value for blc_cost.remarks
     *
     * @mbg.generated Fri May 10 20:47:13 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}