package com.sunlight.blc.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blc_daily_currency
 *
 * @mbg.generated do_not_delete_during_merge Thu May 23 18:55:44 CST 2019
 */
public class DailyCurrency extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.delstatus
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private Integer delstatus;

    /**
     * Database Column Remarks:
     *   货币类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private String currency;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.amount
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private Double amount;

    /**
     * Database Column Remarks:
     *   统计每天的收益id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.daily_profit_id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private Integer dailyProfitId;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_daily_currency.remarks
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.id
     *
     * @return the value of blc_daily_currency.id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.id
     *
     * @param id the value for blc_daily_currency.id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.delstatus
     *
     * @return the value of blc_daily_currency.delstatus
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.delstatus
     *
     * @param delstatus the value for blc_daily_currency.delstatus
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.currency
     *
     * @return the value of blc_daily_currency.currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.currency
     *
     * @param currency the value for blc_daily_currency.currency
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.amount
     *
     * @return the value of blc_daily_currency.amount
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.amount
     *
     * @param amount the value for blc_daily_currency.amount
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.daily_profit_id
     *
     * @return the value of blc_daily_currency.daily_profit_id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public Integer getDailyProfitId() {
        return dailyProfitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.daily_profit_id
     *
     * @param dailyProfitId the value for blc_daily_currency.daily_profit_id
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setDailyProfitId(Integer dailyProfitId) {
        this.dailyProfitId = dailyProfitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_daily_currency.remarks
     *
     * @return the value of blc_daily_currency.remarks
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_daily_currency.remarks
     *
     * @param remarks the value for blc_daily_currency.remarks
     *
     * @mbg.generated Thu May 23 18:55:44 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}