package com.sunlight.blc.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blc_deposit
 *
 * @mbg.generated do_not_delete_during_merge Tue May 07 18:43:18 CST 2019
 */
public class Deposit extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.delstatus
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Integer delstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.account
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.ref_id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Long refId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.status
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.symbol
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.amount
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.create_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.update_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_deposit.remarks
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.id
     *
     * @return the value of blc_deposit.id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.id
     *
     * @param id the value for blc_deposit.id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.delstatus
     *
     * @return the value of blc_deposit.delstatus
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.delstatus
     *
     * @param delstatus the value for blc_deposit.delstatus
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.account
     *
     * @return the value of blc_deposit.account
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.account
     *
     * @param account the value for blc_deposit.account
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.ref_id
     *
     * @return the value of blc_deposit.ref_id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.ref_id
     *
     * @param refId the value for blc_deposit.ref_id
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.status
     *
     * @return the value of blc_deposit.status
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.status
     *
     * @param status the value for blc_deposit.status
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.symbol
     *
     * @return the value of blc_deposit.symbol
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.symbol
     *
     * @param symbol the value for blc_deposit.symbol
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.amount
     *
     * @return the value of blc_deposit.amount
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.amount
     *
     * @param amount the value for blc_deposit.amount
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.create_time
     *
     * @return the value of blc_deposit.create_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.create_time
     *
     * @param createTime the value for blc_deposit.create_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.update_time
     *
     * @return the value of blc_deposit.update_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.update_time
     *
     * @param updateTime the value for blc_deposit.update_time
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_deposit.remarks
     *
     * @return the value of blc_deposit.remarks
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_deposit.remarks
     *
     * @param remarks the value for blc_deposit.remarks
     *
     * @mbg.generated Tue May 07 18:43:18 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}